package hookworm

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	hookScriptContent = `#!/bin/sh
# Generated by hookworm
hookworm assert
`
)

// InstallHook adds hookworm to the .git/hooks/pre-commit file
func InstallHook() error {
	// Find the .git directory
	gitDir, err := findGitDir()
	if err != nil {
		return fmt.Errorf("finding .git directory: %v", err)
	}

	// Define the hook file path
	hookPath := filepath.Join(gitDir, "hooks", "pre-commit")

	// Write the hook script
	err = os.WriteFile(hookPath, []byte(hookScriptContent), 0755)
	if err != nil {
		return fmt.Errorf("writing hook file: %v", err)
	}

	// Ensure the hook is executable
	err = os.Chmod(hookPath, 0755)
	if err != nil {
		return fmt.Errorf("setting hook permissions: %v", err)
	}

	return nil
}

// findGitDir locates the .git directory in the current or parent directories
func findGitDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		gitDir := filepath.Join(dir, ".git")
		if stat, err := os.Stat(gitDir); err == nil && stat.IsDir() {
			return gitDir, nil
		}

		// Move up one directory
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no .git directory found")
		}
		dir = parent
	}
}
